travis:
  secure:
    BINSTAR_TOKEN: BZUZ+5t3Y/e7S52omNbdDS1aO3ha9MRIJqKLH6jAV7guhkNr4kb8THbHy5bnsX/IOG5gklyOaqw2ImADYrMGDqdBO2nKurg90QUo43dL8VuJES5YsVctx1SkPzhQgNFF1WRL9iYgv3tKI+EVL2p1CkxYjLH5xD4X9aUaPrISLbyRpL7INLLSUIFUByPM1yDJV7pnhQufmjt9OVD/OS6YjyUpl0JlbOZBSAezYbImUM+5r5EoC+hI75c6yXDzT4oqJlsDDnHhK4uCF2NjK9KmVLdcriZXwEVoS+TaVHWc27/Ssacc5T16VOw8YY9v3b1sQJZEMQrOLfD7JB0LNDfZ1CDPhBdiOlMsKRf/9y660uzYXH7on/t9kFVLy5ii7hlPpcIbXjaM2I7ZXyTUctaSNQN2fwRntgXv80rCDzHnSuRVGL8BIak2/23xsHdzOH+be8dQXKLXrFWMeyOE0CCod/zVjFaIdo1LXF8yezdT8RvRmXL66dcRCuenVn05jTqG499hGH7B++vYb3rX3mjzzzgnHCC3aoOrJrZFOrd2dya34hMcfGPlBnq2AV98MCnicoEx1ma4IZWr57bnC7S9VLuDE5q7/9h4GOZDHMJOvQIYtBycRKRcybNv+dR8S+EZv197k0x6dAqillyzZVPjCScJO6kcCadDqebmdAwwdgc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
