travis:
  secure:
    BINSTAR_TOKEN: tNuSc4li8rpNGOuB0nJktlmXv0WSYKE2fKtfK1hsvdFcIVXJbveVRG4JWpyVTx9yxQQPYYyprS8yeNq89W1VG1AWD5UljQ/XRgdYQcdZIczwH3G7V7EvTY3jM/1sP//lMFgj4vRlN0GEiqXxyc6OIRqCl9M6NeB8RJv3Sk7PopYeypyDdQN91fh9V24KxJ6LX2cxiH7UnP5ueqR9UyMMrVFUr79qIez4jmpGpXMBqQ1QQ6O97/xqpPi73yIJ+/iJtdWdkXwOPNg3gSUErCwlhALCKgR8F9wdE93pn8dq5FHdUXDcGGOiPSIkkMB7A16/QhG0bqQf3wYqFk30WW4pFbg0iIeltTx80XVxYyLU3kIE3GPL/m2PRV08lt/q9KcjNxnqTvIDfTw48vIo/OQSheKzvRdQ8bDluH/AJoesCVGUYNfqJbBRMCGZjPmRkPtdY0eG55ruRKXBYYnVwqb6YXc7U7/EX7wZipEvDmhwP5LIWkdR4WtDqpk5znPG5EhC2vgaiiL60xzqC+fio9W9wzB0Re/ktHIiXfe+8BOFtsbkSv/COioAsEOWV7kk0yOYeekW6dhxB2WK4GAK+SCzVPv+RTZQoKzsBcK4y4v2pC2+mYRu3fZOJxYv6zp3qbTw1eEDEooyigtUEOix3VJqJ58ZutoW9EdQJ+HCSKJ9X2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
